-- =================================================================================================
-- Problem 1: Database Record Count
-- Business Question:
-- How many customers, orders, order-detail records, products, and categories are stored
-- in the database?
--
-- Goal:
-- Count the number of records in each of the five main tables and combine the results
-- into a single result set.



-- Step 1: Count the number of records in the customers table.

SELECT 
    'customers' AS table_name,       -- 'customers' is a text value, not a column name.
                                     -- AS table_name gives this output column a descriptive alias.

    COUNT(*) AS total_records         -- COUNT(*) counts every row in the customers table.
                                     -- AS total_records gives the calculated result a readable name.

FROM customers                        -- Specifies the table from which the rows are counted.


-- At this point, the query above would return one row similar to:
--
-- table_name     total_records
-- customers      1000
--
-- The same type of query could be written separately for each table. However, running
-- separate SELECT statements would produce separate result sets.
--
-- UNION ALL allows the results of each SELECT statement to be combined vertically
-- into one result set.


UNION ALL                             -- Combines this result with the result of the next SELECT.
                                      -- UNION ALL keeps every returned row.
                                      --
                                      -- UNION could also combine the queries, but UNION removes
                                      -- duplicate rows. Because duplicate removal is unnecessary
                                      -- for this analysis, UNION ALL is the more appropriate choice.


-- Step 2: Repeat the same process for the remaining tables.

SELECT 
    'orders' AS table_name,
    COUNT(*) AS total_records
FROM orders


UNION ALL


SELECT 
    'catagories' AS table_name,       -- "catagories" matches the table name used in this database.
    COUNT(*) AS total_records
FROM catagories


UNION ALL


SELECT 
    'order_details' AS table_name,
    COUNT(*) AS total_records
FROM order_details


UNION ALL


SELECT 
    'products' AS table_name,
    COUNT(*) AS total_records
FROM products;


-- Final Result:
-- The query returns five rows in one result set, with each row showing the total
-- number of records contained in one of the database's main tables.
-- =================================================================================================



-- =================================================================================================
-- Problem 2A: Calculate Total Gross Sales Revenue Before Discounts
-- Business Question:
-- How much sales revenue did the company generate before accounting for discounts?
--
-- Goal:
-- Calculate the total gross revenue generated across all order-detail records.
--
-- Revenue Formula:
-- Revenue per line item = Quantity × UnitPrice
--
-- Because the goal is to calculate revenue BEFORE discounts, DiscountRate is not included
-- in this calculation.



SELECT
    SUM(Quantity * UnitPrice) AS total_revenue
    -- Quantity * UnitPrice calculates the gross revenue generated by each order-detail record.
    --
    -- For example:
    -- If Quantity = 3 and UnitPrice = $10.00:
    --
    -- 3 × $10.00 = $30.00 in gross revenue
    --
    -- SUM(...) then adds the revenue from every order-detail record together to calculate
    -- the company's total gross sales revenue.
    --
    -- AS total_revenue assigns a descriptive alias to the calculated output column.

FROM order_details;
    -- Specifies that Quantity and UnitPrice are retrieved from the order_details table.


-- Final Result:
-- Total Gross Revenue = $791,932.47
--
-- Interpretation:
-- The company generated $791,932.47 in gross sales revenue across all order-detail
-- records before accounting for customer discounts.
--
-- Important:
-- Revenue is not the same as profit. This calculation measures the value of sales
-- before discounts and does not subtract product costs or other business expenses.

-- =================================================================================================



-- =================================================================================================
-- Problem 2B: Calculate Total Revenue After Discounts
-- Business Question:
-- How much sales revenue did the company actually generate after accounting for discounts?
--
-- Goal:
-- Calculate gross sales revenue and subtract the total dollar amount given to customers
-- through discounts.
--
-- Formula:
-- Revenue After Discounts = Gross Revenue - Total Discount Amount
--
-- Gross Revenue         = Quantity × UnitPrice
-- Total Discount Amount = Quantity × UnitPrice × DiscountRate



SELECT
    SUM(Quantity * UnitPrice)
    -
    SUM(Quantity * UnitPrice * DiscountRate)
    AS total_revenue_after_discounts

    -- SUM(Quantity * UnitPrice) calculates the company's total gross revenue before
    -- any discounts are applied.
    --
    -- SUM(Quantity * UnitPrice * DiscountRate) calculates the total dollar amount
    -- deducted from sales because of discounts.
    --
    -- The query subtracts the discount amount from gross revenue:
    --
    -- SUM() performs these calculations across all order-detail records.
    --
    -- AS total_revenue_after_discounts assigns a descriptive alias to the
    -- final calculated output column.

FROM order_details;
    -- Specifies that Quantity, UnitPrice, and DiscountRate are retrieved
    -- from the order_details table.


-- Final Result:
-- Total Revenue After Discounts = $761,951.13
--
-- Interpretation:
-- After accounting for customer discounts, the company generated approximately
-- $761,951.13 in sales revenue.
--
-- Compared with the gross revenue calculated in Problem 2A:
--
-- Gross Revenue:                    $791,932.47
-- Revenue After Discounts:          $761,951.13
-- Difference Due to Discounts:       $29,981.34
--
-- Important:
-- This calculation accounts for discounts, but it still represents revenue rather
-- than profit. Product costs and other business expenses have not been subtracted.
-- =================================================================================================



-- =================================================================================================
-- Problem 3: Identify the Highest-Revenue Customers
-- Business Question:
-- Which customers generate the most gross sales revenue for the company?
--
-- Goal:
-- Calculate total gross revenue for each customer and rank customers from the
-- highest revenue generator to the lowest.
--
-- Revenue Formula:
-- Revenue per Line Item = Quantity × UnitPrice
--
-- Customer Revenue = SUM(Quantity × UnitPrice) for all purchases made by that customer


SELECT
    c.Customer_ID,

    -- Retrieves the Customer_ID so each customer can be identified in the result.
    --
    -- The "c." prefix specifies that Customer_ID is being retrieved from the
    -- customers table, which has been assigned the alias "c".


    SUM(od.Quantity * od.UnitPrice) AS total_revenue

    -- Quantity * UnitPrice calculates the gross revenue generated by each
    -- individual order-detail record.
    --
    -- SUM(...) adds together the revenue from all order-detail records
    -- associated with the same customer.


FROM customers AS c

    -- Begins with the customers table.
    -- AS c assigns "c" as a temporary alias for easier reference.


JOIN orders AS o
    ON c.Customer_ID = o.Customer_ID

    -- Connects customers to their orders using Customer_ID.
    --
    -- Customer_ID represents the same customer in both tables, allowing SQL
    -- to determine which orders belong to each customer.


JOIN order_details AS od
    ON od.Order_ID = o.Order_ID

    -- Connects each order to its corresponding order-detail records using Order_ID.
    --
    -- The orders table acts as the bridge between customers and order_details:
    --
    -- customers → orders → order_details
    --
    -- This allows the Quantity and UnitPrice values from each purchase to be
    -- associated with the customer who placed the order.


GROUP BY c.Customer_ID

    -- GROUP BY places all records belonging to the same customer into one group.
    --
    -- SUM(Quantity * UnitPrice) is then calculated separately for each customer.
    --
    -- This transforms multiple purchase records into one summarized revenue
    -- result for each customer.


ORDER BY total_revenue DESC;

    -- ORDER BY determines how the final result set is sorted.
    --
    -- total_revenue refers to the alias created earlier for:
    --
    -- SUM(od.Quantity * od.UnitPrice)
    --
    -- DESC means "descending," which sorts numerical values from highest to lowest.
    --
    -- Therefore, the customer generating the most revenue appears at the top
    -- of the result set, followed by the next highest-revenue customer, and so on.
    --
    -- ASC (ascending) would do the opposite and sort from lowest to highest.



-- Interpretation:
-- Based on gross revenue, CSTMR0127 is the highest-revenue customer in the dataset,
-- generating $3,396.19 in sales.



-- Important:
-- This query ranks customers by GROSS REVENUE, not by profit.
--
-- Discounts are not deducted because DiscountRate is not included in the calculation,
-- and product costs are not deducted because UnitCost is not included.
--
-- Therefore, a customer appearing near the top generated a large amount of sales,
-- but this does not necessarily mean they were one of the company's most profitable
-- customers.
-- =================================================================================================



-- =================================================================================================
-- Problem 4: Identify the Products That Generate the Most Profit
-- Business Question:
-- Which products generate the highest total profit for the company?
--
-- Goal:
-- Calculate the profit generated by each product across all order-detail records,
-- display the corresponding product name, and rank products from highest to lowest profit.
--
-- Profit Formula:
--
-- Profit per Unit = UnitPrice - UnitCost
--
-- Profit per Line Item = Quantity × (UnitPrice - UnitCost)
--
-- Total Product Profit = SUM(Quantity × (UnitPrice - UnitCost))




SELECT
    od.Product_ID,

    -- Retrieves the Product_ID from the order_details table.
    --
    -- Product_ID uniquely identifies which product is associated with each
    -- order-detail record.


    p.ProductName,

    -- Retrieves the corresponding product name from the products table.
    --
    -- ProductName makes the final result easier to interpret than displaying
    -- only the Product_ID.


    SUM(od.Quantity * (od.UnitPrice - od.UnitCost)) AS total_profit

    -- od.UnitPrice - od.UnitCost calculates the profit earned from ONE unit.
    
    -- The result is then multiplied by Quantity to calculate the profit
    -- generated by the entire order-detail record.
    
    -- SUM(...) adds together the profit from every order-detail record
    -- associated with the same product.
 
    -- AS total_profit assigns a descriptive alias to the calculated column.


FROM order_details AS od

    -- Begins with the order_details table because it contains the values needed
    -- for the profit calculation:
    --
    -- Product_ID
    -- Quantity
    -- UnitPrice
    -- UnitCost
    --
    -- AS od assigns "od" as a temporary alias for the order_details table.


JOIN products AS p
    ON od.Product_ID = p.Product_ID

    -- Connects order_details to the products table using Product_ID.
    --
    -- Product_ID represents the same product in both tables:
    --
    -- order_details.Product_ID = identifies the product purchased
    -- products.Product_ID      = identifies the product and its descriptive information
    --
    -- This JOIN allows the ProductName stored in the products table to be displayed
    -- alongside the sales and profit information stored in order_details.


GROUP BY od.Product_ID, p.ProductName

    -- GROUP BY places all order-detail records belonging to the same product
    -- into a group.
    --
    -- SUM(...) then calculates total profit separately for each product.
    --
    -- Both Product_ID and ProductName are included because they appear in the
    -- SELECT statement without being inside an aggregate function such as SUM().


ORDER BY total_profit DESC;

    -- ORDER BY sorts the completed product-level results using total_profit.


-- Interpretation:
-- Based on this profit calculation, ABC's Ground Beef generated the highest
-- total profit in the dataset at approximately $14,438.44.
--
-- Ranking products by total profit helps identify which products contribute
-- the greatest amount of gross profit to the business.


-- Important:
-- This calculation is different from the revenue calculations used previously.
--
-- Revenue:
-- Quantity × UnitPrice
--
-- Profit used in this analysis:
-- Quantity × (UnitPrice - UnitCost)
--
-- Revenue measures how much money is generated from sales, while this profit
-- calculation also accounts for the recorded cost of the products sold.
--
-- However, this is a simplified product-level gross profit calculation.
-- It does not account for discounts, returns, taxes, shipping, labor,
-- overhead, or other operating expenses.
--
-- Therefore, "total_profit" in this query should not be interpreted as the
-- company's final net profit.
-- =================================================================================================



-- =================================================================================================
-- Problem 5: Identify the Product Categories That Generate the Most Profit
-- Business Question:
-- Which product categories generate the highest total profit for the company?
--
-- Goal:
-- Connect order-detail records to their products and product categories, calculate
-- the profit generated from sales, and group those profits by category.
--
-- Profit Formula:
--
-- Profit per Unit = UnitPrice - UnitCost
--
-- Profit per Line Item = Quantity × (UnitPrice - UnitCost)
--
-- Total Category Profit = SUM(Quantity × (UnitPrice - UnitCost))


SELECT
    c.CatagoryName,

    -- Retrieves the name of each product category from the catagories table.
    --
    -- The "c." prefix specifies that CatagoryName comes from the table assigned
    -- the alias "c".


    SUM(od.Quantity * (od.UnitPrice - od.UnitCost)) AS total_profit

    -- od.UnitPrice - od.UnitCost calculates the profit generated from ONE unit.
    
    -- Multiplying the profit per unit by Quantity calculates the profit generated
    -- by the entire order-detail record.
    
    -- SUM(...) adds together the profit from all order-detail records belonging
    -- to products within the same category.

    -- AS total_profit assigns a descriptive alias to the calculated output column.


FROM order_details AS od

    -- Begins with the order_details table because it contains the values required
    -- for the profit calculation:
    --
    -- Product_ID
    -- Quantity
    -- UnitPrice
    -- UnitCost
    --
    -- AS od assigns "od" as a temporary alias for the order_details table.


JOIN products AS p
    ON od.Product_ID = p.Product_ID

    -- Connects each order-detail record to its corresponding product using Product_ID.
    --
    -- The products table contains the Catagory_ID associated with each product.
    --
    -- This connection is necessary because order_details does not directly contain
    -- information about the category to which a product belongs.


JOIN catagories AS c
    ON c.Catagory_ID = p.Catagory_ID

    -- Connects each product to its corresponding category using Catagory_ID.
    --
    -- products.Catagory_ID identifies the category assigned to each product.
    -- catagories.Catagory_ID identifies that category in the catagories table.
    --
    -- This second JOIN allows SQL to retrieve CatagoryName for each product.
    --
    -- SQL can now follow the complete relationship:
    --
    -- order_details → products → catagories
    
GROUP BY c.CatagoryName

    -- GROUP BY places all records associated with the same product category
    -- into one group.
    --
    -- SUM(...) then calculates total profit separately for each category.
    --
    -- Unlike Problem 4, where profit was grouped by individual product,
    -- this query combines the profits of ALL products belonging to the
    -- same category.
    


ORDER BY total_profit DESC;

    -- ORDER BY sorts the completed category-level results using total_profit.
    --
    -- DESC means descending order, so the category generating the highest
    -- total profit appears first.
    --
    -- The remaining categories are then ranked from highest to lowest profit.


-- Final Result:
-- The query returns one row for each product category and ranks the categories
-- according to the total profit generated.



-- Interpretation:
-- Meat & Poultry generated the highest total product-level gross profit in the
-- dataset at approximately $77,308.34.
--
-- Grouping profit by category provides a broader view of product performance than
-- analyzing individual products alone. This can help identify which areas of the
-- company's product catalog contribute the most gross profit.


-- Important:
-- The products table is essential to this query because order_details does not
-- contain Catagory_ID or CatagoryName.
--
-- Therefore, SQL cannot directly connect:
--
-- order_details → catagories
--
-- Instead, products acts as the bridge:
--
-- order_details → products → catagories
--
-- This is similar to how the orders table acted as the bridge between customers
-- and order_details in the previous customer analysis.


-- Important Profit Note:
-- As in Problem 4, "total_profit" represents a simplified product-level gross
-- profit calculation:
--
-- Quantity × (UnitPrice - UnitCost)
--
-- This calculation does not account for discounts, returns, shipping, labor,
-- taxes, overhead, or other operating expenses.
--
-- Therefore, the results should not be interpreted as final company net profit.
-- =================================================================================================



-- =================================================================================================
-- Problem 6: Identify the Products With the Highest Return Rates
-- Business Question:
-- Which products have the highest percentage of order-detail records marked as returned?
--
-- Goal:
-- Count the total number of order-detail records for each product, determine how many
-- of those records were returned, calculate the return rate as a percentage, and rank
-- products from highest to lowest return rate.
--
-- Return Rate Formula:
--
--                         Number of Returned Records
-- Return Rate (%) =     ----------------------------- × 100
--                         Total Order-Detail Records
--
-- In this dataset:
--
-- IsReturned = 1  →  The order-detail record was returned.
-- IsReturned = 0  →  The order-detail record was not returned.



SELECT
    od.Product_ID,

    -- Retrieves the Product_ID associated with each group of order-detail records.
    --
    -- The "od." prefix specifies that Product_ID is being retrieved from the
    -- order_details table.


    p.ProductName,

    -- Retrieves the corresponding product name from the products table.
    --
    -- Including ProductName makes the final results easier to understand than
    -- displaying only the Product_ID.


    COUNT(*) AS total_records,

    -- COUNT(*) counts the total number of order-detail records associated
    -- with each product.
    --
    -- Because the query is grouped by product later, COUNT(*) is calculated
    -- separately for each product.


    SUM(
        CASE
            WHEN od.IsReturned = 1 THEN 1
            ELSE 0
        END
    ) AS total_returns,

    -- CASE allows SQL to perform conditional logic on each record.
    --
    -- For every order-detail record, SQL checks the IsReturned column:
    --
    -- WHEN IsReturned = 1 THEN 1
    --     If the record was returned, assign it a value of 1.
    --
    -- ELSE 0
    --     If the record was not returned, assign it a value of 0.
    --
    -- SUM(...) then adds those values:
    --
    -- 0 + 1 + 0 + 1 + 1 = 3 returns
    --
    -- This allows the query to count only the records where IsReturned = 1.
    --
    -- AS total_returns assigns a descriptive alias to the calculated column.


    ROUND(
        SUM(
            CASE
                WHEN od.IsReturned = 1 THEN 1
                ELSE 0
            END
        )
        / COUNT(*) * 100,
        2
    ) AS return_rate

    -- This calculation converts the number of returned records into a percentage.
    --
    -- The numerator:
    --
    -- SUM(CASE WHEN IsReturned = 1 THEN 1 ELSE 0 END)
    --
    -- counts how many records for the product were returned.
    --
    -- The denominator:
    --
    -- COUNT(*)
    --
    -- counts the total number of order-detail records for that product.
    --
    -- Dividing total returns by total records gives the proportion of records
    -- that were returned.
   --
    -- Multiplying by 100 converts the decimal proportion into a percentage:
    --
    -- ROUND(..., 2) rounds the final return rate to two decimal places.
    --
    -- AS return_rate assigns a descriptive alias to the calculated percentage.


FROM order_details AS od

    -- Begins with the order_details table because it contains Product_ID
    -- and the IsReturned indicator needed for the return analysis.
    --
    -- AS od assigns "od" as a temporary alias for order_details.


JOIN products AS p
    ON od.Product_ID = p.Product_ID

    -- Connects each order-detail record to its corresponding product using Product_ID.
    --
    -- This JOIN allows the ProductName from the products table to be displayed
    -- alongside the return information stored in order_details.


GROUP BY od.Product_ID, p.ProductName

    -- GROUP BY places all order-detail records belonging to the same product
    -- into one group.
    --
    -- COUNT(*) and SUM(CASE...) are then calculated separately for each product.
    --


ORDER BY return_rate DESC;

    -- ORDER BY sorts the completed results using the calculated return_rate.
    --
    -- DESC means descending order, so products with the highest return rates
    -- appear at the top of the result set.
    --
    -- This makes products with unusually high return rates easier to identify
    -- for further investigation.


-- Interpretation:
-- Products appearing near the top of the result have a larger percentage of their
-- order-detail records marked as returned.
--
-- A high return rate can be useful as an indicator for further investigation into
-- areas such as product quality, customer expectations, product descriptions,
-- fulfillment issues, or other possible causes.
--
-- However, this query identifies the return pattern; it does not determine WHY
-- customers returned a product.


-- Important:
-- This query calculates a RECORD-LEVEL return rate rather than a UNIT-LEVEL return rate.
--
-- COUNT(*) counts order-detail records, not the total Quantity of products purchased.
--

-- =================================================================================================



-- =================================================================================================
-- Problem 7: Analyze Month-over-Month Revenue Growth
-- Business Question:
-- How is the company's gross sales revenue changing from month to month?
-- Are monthly sales increasing or decreasing compared with the previous month?
--
-- Goal:
-- 1. Calculate total gross revenue for each month.
-- 2. Retrieve the previous month's revenue.
-- 3. Compare the current month with the previous month.
-- 4. Calculate the percentage increase or decrease in revenue.
--
-- Revenue Formula:
-- Monthly Revenue = SUM(Quantity × UnitPrice)
--
-- Month-over-Month (MoM) Growth Formula:
--
--                         Current Month Revenue - Previous Month Revenue
-- Growth Percentage =    ------------------------------------------------ × 100
--                                   Previous Month Revenue


-- Step 1: Create a Common Table Expression (CTE) containing monthly revenue.

WITH monthly_sales AS (

    -- WITH creates a Common Table Expression (CTE).
    --
    -- A CTE can be thought of as a temporary named result set that exists only
    -- while this query is running.
    --
    -- The name "monthly_sales" allows the monthly revenue results calculated
    -- below to be referenced by the final SELECT statement.


    SELECT
        DATE_FORMAT(o.OrderDate, '%Y-%m') AS month,

        -- DATE_FORMAT() converts each OrderDate into a Year-Month format.
        --
        -- Using '%Y-%m' preserves both the year and month.
        --
        -- This is important because grouping only by the month number could
        -- incorrectly combine the same month from different years.
        --
        -- AS month assigns a readable alias to the formatted date.


        SUM(od.Quantity * od.UnitPrice) AS monthly_revenue

        -- Quantity * UnitPrice calculates gross revenue for each order-detail record.
        --
        -- SUM(...) adds together all revenue associated with orders occurring
        -- within the same month.
        --
        -- Because the records are grouped by Year-Month below, SQL calculates
        -- one gross revenue total for each month.
        --
        -- AS monthly_revenue assigns a descriptive alias to the calculated result.


    FROM orders AS o

        -- Begins with the orders table because it contains OrderDate, which is
        -- necessary to determine when each sale occurred.


    JOIN order_details AS od
        ON o.Order_ID = od.Order_ID

        -- Connects each order to its corresponding order-detail records using Order_ID.
        --
        -- The orders table provides the date of the transaction, while order_details
        -- provides Quantity and UnitPrice.
     


    GROUP BY DATE_FORMAT(o.OrderDate, '%Y-%m')

        -- GROUP BY places all orders occurring within the same Year-Month
        -- into the same group.
        --
        -- SUM(Quantity * UnitPrice) is then calculated separately for each month.


)


-- Step 2: Compare each month's revenue with the previous month.

SELECT
    month,

    -- Displays the Year-Month created inside the monthly_sales CTE.


    monthly_revenue,

    -- Displays the total gross revenue calculated for the current month.


    LAG(monthly_revenue) OVER (ORDER BY month) AS previous_month_revenue,

    -- LAG() is a window function that retrieves a value from a previous row
    -- without removing or combining the current rows.
    --
    -- In this case:
    --
    -- LAG(monthly_revenue)
    --
    -- asks SQL to retrieve the monthly_revenue value from the previous row.
    --
    -- OVER (ORDER BY month) tells SQL how the rows should be arranged before
    -- determining which row counts as the "previous" row.
    


    ROUND(
        (
            monthly_revenue
            - LAG(monthly_revenue) OVER (ORDER BY month)
        )
        /
        LAG(monthly_revenue) OVER (ORDER BY month)
        * 100,
        2
    ) AS growth_percentage

    -- This calculation determines the percentage change in revenue between
    -- the current month and the previous month.
    --
    -- Step 1:
    -- Current Revenue - Previous Revenue
    --
    -- This determines the dollar change between the two months.
    --
    -- Step 2:
    -- Divide the change by the PREVIOUS month's revenue:
    --
    -- Step 3:
    -- Multiply by 100 to convert the decimal into a percentage:
    --
    -- ROUND(..., 2) rounds the final percentage to two decimal places.
    --
    -- AS growth_percentage assigns a descriptive alias to the calculated result.


FROM monthly_sales;

    -- The final SELECT retrieves its data from the monthly_sales CTE rather
    -- than directly from the original tables.
    --
    -- At this stage, monthly_sales already contains one row per month, making
    -- it easier to compare each month's revenue with the previous month.




-- Important:
-- This query calculates GROSS revenue because it uses:
--
-- Quantity × UnitPrice
--
-- Discounts, product costs, returns, and other expenses are not included.
--
-- Therefore, growth_percentage measures the month-over-month percentage change
-- in gross sales revenue, not profit.
-- =================================================================================================



-- =================================================================================================
-- Problem 8: Identify the Most Valuable Repeat Customers
-- Business Question:
-- Which customers have purchased from the company more than once, and which of those
-- repeat customers generated the most gross revenue?
--
-- Goal:
-- 1. Count the number of unique orders placed by each customer.
-- 2. Calculate the total gross revenue generated by each customer.
-- 3. Keep only customers who placed more than one order.
-- 4. Rank those repeat customers from highest to lowest revenue.
--
-- Repeat Customer Definition:
-- A repeat customer is defined in this analysis as a customer who has placed
-- more than one distinct order.
--
-- Revenue Formula:
-- Customer Revenue = SUM(Quantity × UnitPrice)



SELECT
    o.Customer_ID,

    -- Retrieves the Customer_ID associated with each order.
    --
    -- Customer_ID identifies which customer placed each order.
    --
    -- Because the query will later GROUP BY Customer_ID, the final result
    -- will contain one summarized row for each repeat customer.


    COUNT(DISTINCT o.Order_ID) AS total_orders,

    -- COUNT() counts values within each customer's group.
    --
    -- DISTINCT tells SQL to count each Order_ID only once.
    --
    -- This is especially important because joining orders to order_details
    -- can cause the same Order_ID to appear multiple times.
    
    -- AS total_orders assigns a descriptive alias to the calculated column.


    SUM(od.Quantity * od.UnitPrice) AS total_revenue

    -- Quantity * UnitPrice calculates the gross revenue generated by each
    -- individual order-detail record.
    --
    -- SUM(...) then adds together the revenue from all order-detail records
    -- associated with the same customer.
    --
    -- AS total_revenue assigns a descriptive alias to the calculated column.


FROM orders AS o

    -- Begins with the orders table.
    --
    -- The orders table contains both Customer_ID and Order_ID, allowing the query
    -- to determine which orders belong to each customer.
    --
    -- AS o assigns "o" as a temporary alias for the orders table.


JOIN order_details AS od
    ON od.Order_ID = o.Order_ID

    -- Connects each order to its corresponding order-detail records using Order_ID.
    --
    -- The orders table provides the customer associated with each order.
    -- The order_details table provides the Quantity and UnitPrice needed to
    -- calculate revenue.
    --
    -- Together, the relationship allows SQL to determine:
    --
    -- Customer → Order → Purchases → Revenue


GROUP BY o.Customer_ID

    -- GROUP BY places all records belonging to the same customer into one group.
    --
    -- The aggregate functions are then calculated separately for each customer:
    --
    -- COUNT(DISTINCT Order_ID) → Number of unique orders
    -- SUM(Quantity * UnitPrice) → Total gross revenue
    

HAVING COUNT(DISTINCT o.Order_ID) > 1

    -- HAVING filters the results AFTER the records have been grouped.
    --
    -- This condition keeps only customers who placed more than one
    -- distinct order.
    --
    -- HAVING is used instead of WHERE because total_orders is based on
    -- an aggregate calculation: COUNT(DISTINCT Order_ID).
    --
    -- SQL must first group the records and count each customer's orders
    -- before it can determine whether that customer has more than one order.


ORDER BY total_revenue DESC;

    -- ORDER BY sorts the remaining repeat customers according to total_revenue.
    --
    -- DESC means descending order, so the repeat customer who generated the
    -- highest gross revenue appears first.
    --
    -- This allows the analysis to identify not only who purchased repeatedly,
    -- but also which repeat customers contributed the most revenue.



-- Interpretation:
-- CSTMR0127 generated the highest gross revenue among the repeat customers
-- identified by this query, producing approximately $3,396.19 across 11 orders.
--
-- The results also demonstrate that purchase frequency and revenue do not
-- necessarily move together.
--
-- CSTMR0104 placed more orders, but CSTMR0127 generated more total revenue.
--
-- This means that simply having the highest number of orders does not necessarily
-- make a customer the highest-revenue customer. Order values also matter.


-- Important:
-- This query defines a repeat customer specifically as someone who has placed
-- more than ONE distinct order.
--
-- COUNT(DISTINCT Order_ID) is important because the JOIN with order_details can
-- create multiple rows for a single order when that order contains multiple products.
--
-- Without DISTINCT, the query could mistakenly count order-detail records as
-- separate orders and overstate how frequently a customer purchased.


-- Important Revenue Note:
-- This query calculates GROSS revenue using:
--
-- Quantity × UnitPrice
--
-- It does not subtract discounts, product costs, returns, or other expenses.
--
-- Therefore, total_revenue represents gross sales revenue rather than profit.


-- WHERE vs. HAVING:
--
-- WHERE:
-- Filters individual records BEFORE GROUP BY occurs.
--
-- HAVING:
-- Filters summarized groups AFTER GROUP BY occurs.
-- =================================================================================================



-- =================================================================================================
-- Problem 9: Identify Customers Who May Be Becoming Inactive
-- Business Question:
-- Which customers have not made a purchase recently and may be becoming inactive?
--
-- Goal:
-- 1. Find each customer's most recent purchase date.
-- 2. Calculate how many days have passed since that purchase.
-- 3. Identify customers whose most recent purchase was more than 180 days before
--    the latest date represented in the dataset.
-- 4. Rank those customers from longest inactive period to shortest.
--
-- Inactivity Definition:
-- For this analysis, a customer is considered potentially inactive if their
-- most recent purchase occurred more than 180 days before 2026-06-01.
--
-- Reference Date:
-- 2026-06-01 is used because it is the latest OrderDate in this dataset.
-- Using the dataset's latest date keeps the analysis aligned with the period
-- represented by the data rather than comparing historical data with today's date.


SELECT
    Customer_ID,

    -- Retrieves the Customer_ID from the orders table.
    --
    -- Because the query will later GROUP BY Customer_ID, the final result
    -- will contain one summarized row for each customer who meets the
    -- inactivity condition.


    MAX(OrderDate) AS last_purchase_date,

    -- A customer may have multiple orders and therefore multiple OrderDate values.
    --
    -- MAX(OrderDate) finds the latest (most recent) OrderDate for each customer.
    --
    -- With dates, MAX() returns the greatest/latest date.
    --
    -- AS last_purchase_date assigns a descriptive alias to the calculated result.


    DATEDIFF('2026-06-01', MAX(OrderDate)) AS days_since_last_purchase

    -- DATEDIFF() calculates the number of days between two dates.
    --
    -- Syntax:
    --
    -- DATEDIFF(later_date, earlier_date)
    --
    -- In this query:
    --
    -- Later Date   = 2026-06-01
    -- Earlier Date = Customer's most recent OrderDate
    --
    -- SQL therefore calculates:
    --
    -- 2026-06-01 - last_purchase_date
    --
    -- Example:
    --
    -- Reference Date       = 2026-06-01
    -- Last Purchase Date   = 2025-11-10
    --
    -- DATEDIFF determines how many days passed between those dates.
    --
    -- A larger number means the customer has gone a longer period without
    -- making another purchase.
    --
    -- AS days_since_last_purchase assigns a descriptive alias to this calculation.


FROM orders

    -- The orders table contains all information required for this analysis:
    --
    -- Customer_ID = identifies who placed the order.
    -- OrderDate    = identifies when the order was placed.
    --
    -- No JOIN is necessary because both required columns are already stored
    -- in the same table.


GROUP BY Customer_ID

    -- GROUP BY places all orders belonging to the same customer into one group.
    --
    -- MAX(OrderDate) is then calculated separately for each customer.
    --
    -- SQL has reduced multiple orders per customer into one record showing
    -- each customer's most recent purchase.


HAVING DATEDIFF('2026-06-01', MAX(OrderDate)) > 180

    -- HAVING filters the customer groups after MAX(OrderDate) has been calculated.
    --
    -- The query keeps only customers whose most recent purchase occurred
    -- more than 180 days before the reference date.
    --
    -- HAVING is appropriate because the condition depends on MAX(OrderDate),
    -- which is an aggregate calculation performed for each customer group.


ORDER BY days_since_last_purchase DESC;

    -- ORDER BY sorts the remaining customers according to the number of days
    -- since their most recent purchase.
    --
    -- DESC means descending order, so the largest number appears first.
    --
    -- Therefore, customers who have gone the longest without purchasing
    -- appear at the top of the result.
    --
    -- This makes the customers with the longest periods of inactivity
    -- immediately visible.


-- Final Result:
-- The query returns customers whose most recent purchase was more than
-- 180 days before the dataset's reference date.
--
-- The customers are ranked from the longest period without a purchase
-- to the shortest period that still exceeds the 180-day threshold.


-- Interpretation:
-- Customers appearing in this result have gone more than approximately
-- six months without making another purchase as of 2026-06-01.
--
-- Customers near the top of the result have gone the longest without
-- purchasing and may warrant further investigation for possible inactivity.
--
-- From a business perspective, this type of analysis could help identify
-- customer groups for retention analysis, re-engagement campaigns, or
-- additional investigation into purchasing behavior.


-- Important:
-- This query does NOT prove that a customer has permanently stopped purchasing
-- or has been lost as a customer.
--
-- It only identifies customers who meet the inactivity rule established
-- for this analysis:
--
-- More than 180 days since their most recent purchase.
--
-- Therefore, terms such as "potentially inactive" or "inactive based on the
-- 180-day threshold" are more accurate than stating that these customers
-- have definitely been lost.


-- Why 2026-06-01 Is Used Instead of Today's Date:
--
-- The dataset's latest OrderDate is 2026-06-01.
--
-- If CURRENT_DATE() were used while analyzing a historical or static dataset,
-- every customer's inactivity period would continue increasing even though
-- the dataset itself contains no newer transactions.
--
-- Using the maximum date represented in the dataset creates a fairer comparison:
--
-- "How long had this customer been inactive as of the end of the available data?"
--
-- rather than:
--
-- "How long has it been since their purchase compared with today's real-world date?"
-- =================================================================================================



-- =================================================================================================
-- Problem 10: Calculate the Percentage of Revenue Generated by the Top 10% of Customers
-- Business Question:
-- What percentage of the company's total gross revenue is generated by its
-- highest-revenue customers?
--
-- Goal:
-- 1. Calculate total gross revenue generated by each customer.
-- 2. Rank customers from highest to lowest revenue.
-- 3. Select the top 100 customers.
-- 4. Calculate the combined revenue generated by those customers.
-- 5. Compare their combined revenue with total company revenue.
-- 6. Express the result as a percentage.
--
-- Dataset Assumption:
-- The dataset contains 1,000 customers.
--
-- Therefore:
--
-- 1,000 × 10% = 100 customers
--
-- Selecting the top 100 customers represents the top 10% of customers
-- in this specific dataset.
--
-- Revenue Formula:
-- Customer Revenue = SUM(Quantity × UnitPrice)
--
-- Revenue Share Formula:
--
--                         Revenue from Top 100 Customers
-- Top 10% Revenue Share = -------------------------------- × 100
--                              Total Company Revenue



-- Step 1: Create a CTE containing the 100 highest-revenue customers.

WITH top_customers AS (

    -- WITH creates a Common Table Expression (CTE).
    --
    -- The CTE creates a temporary named result set called "top_customers"
    -- that can be referenced by the main query below.
    --
    -- This CTE will contain only the 100 customers who generated the
    -- highest amount of gross revenue.


    SELECT
        o.Customer_ID,

        -- Retrieves the Customer_ID associated with each order.
        --
        -- Customer_ID will later be used to group all purchases belonging
        -- to the same customer.


        SUM(od.Quantity * od.UnitPrice) AS total_revenue

        -- Quantity * UnitPrice calculates gross revenue for each
        -- individual order-detail record.
        --
        -- SUM(...) adds together all order-detail revenue belonging
        -- to the same customer.
        --
        -- AS total_revenue assigns a descriptive alias to the calculation.


    FROM orders AS o

        -- Begins with the orders table because it contains Customer_ID,
        -- which identifies the customer who placed each order.


    JOIN order_details AS od
        ON od.Order_ID = o.Order_ID

        -- Connects each order to its corresponding order-detail records
        -- using Order_ID.
        --
        -- The orders table tells us WHICH CUSTOMER placed the order.
        --
        -- The order_details table provides Quantity and UnitPrice,
        -- which are needed to calculate revenue.
        --
        -- Together:
        --
        -- Customer → Order → Order Details → Revenue


    GROUP BY o.Customer_ID

        -- GROUP BY places all order-detail records belonging to the same
        -- customer into one group.
        --
        -- SUM(Quantity * UnitPrice) is then calculated separately
        -- for each customer.


    ORDER BY total_revenue DESC

        -- ORDER BY sorts customers according to total revenue.
        --
        -- DESC means descending order, so the highest-revenue customer
        -- appears first.
        --
        -- This sorting is necessary because LIMIT 100 will select the
        -- first 100 customers from this ranked result.


    LIMIT 100

        -- LIMIT 100 keeps only the first 100 customers after the results
        -- have been sorted from highest to lowest revenue.
        --
        -- Since this dataset contains 1,000 customers:
        --
        -- 100 / 1,000 × 100 = 10%
        --
        -- Therefore, these 100 customers represent the top 10% of customers
        -- based on gross revenue generated.

)


-- Step 2: Calculate what percentage of total company revenue comes
-- from the top 100 customers.

SELECT
    ROUND(
        SUM(total_revenue)
        /
        (
            SELECT SUM(Quantity * UnitPrice)
            FROM order_details
        )
        * 100,
        2
    ) AS top_10_percent_revenue_share

    -- SUM(total_revenue) adds together the revenue generated by all
    -- 100 customers stored inside the top_customers CTE.
    --
    -- In this dataset:
    --
    -- Top 100 Customer Revenue = approximately $209,472.99
    --
    -- This becomes the NUMERATOR of the percentage calculation.
    --
    --
    -- The subquery:
    --
    -- (
    --     SELECT SUM(Quantity * UnitPrice)
    --     FROM order_details
    -- )
    --
    -- independently calculates total gross revenue generated by the
    -- entire company across all order-detail records.
    --
    -- In this dataset:
    --
    -- Total Company Gross Revenue = approximately $791,932.47
    --
    -- This becomes the DENOMINATOR.
    --
    -- Therefore, the calculation is approximately:
    --
    -- $209,472.99
    -- ----------- × 100
    -- $791,932.47
    --
    -- ≈ 26.45%
    --
    -- ROUND(..., 2) rounds the final percentage to two decimal places.
    --
    -- AS top_10_percent_revenue_share assigns a descriptive name
    -- to the final calculated result.


FROM top_customers;

    -- The outer query retrieves its numerator from the top_customers CTE.
    --
    -- Since the CTE contains only the 100 highest-revenue customers,
    -- SUM(total_revenue) represents the combined gross revenue generated
    -- by the top 10% of customers.


-- Final Result:
--
-- top_10_percent_revenue_share
-- -----------------------------
--             26.45
--
-- The top 10% of customers generated approximately 26.45% of the
-- company's total gross revenue represented in this dataset.


-- Interpretation:
-- Although the top 100 customers represent only 10% of the 1,000 customers,
-- they account for approximately 26.45% of total gross revenue.
--
-- This indicates that revenue is not distributed evenly across customers.
-- The highest-revenue 10% contribute a disproportionately larger share
-- of total gross sales.
--
-- This information could be useful for customer segmentation, retention
-- analysis, loyalty programs, and understanding how dependent the business
-- is on its highest-revenue customers.


-- Important:
-- This analysis ranks customers using GROSS REVENUE:
--
-- Quantity × UnitPrice
--
-- It does not account for:
--
-- • Discounts
-- • Product costs
-- • Returns
-- • Shipping expenses
-- • Taxes
-- • Other operating expenses
--
-- Therefore, the result represents the top customers by gross sales revenue,
-- not necessarily the company's most profitable customers.


-- Important:
-- LIMIT 100 does NOT automatically mean "top 10%."
--
-- It means exactly:
--
-- "Return the first 100 rows."
--
-- In this analysis, those 100 rows represent 10% because the dataset contains
-- exactly 1,000 customers:
--
-- 100 / 1,000 = 0.10 = 10%
--
-- If the dataset contained a different number of customers, LIMIT 100 would
-- no longer necessarily represent the top 10%.


-- How the Query Works From Beginning to End:
--
-- Start with all orders and order details
--                 ↓
-- Calculate revenue for each purchase
--                 ↓
-- GROUP BY Customer_ID
--                 ↓
-- Calculate total revenue for each customer
--                 ↓
-- ORDER BY total_revenue DESC
--                 ↓
-- LIMIT 100
--                 ↓
-- Top 100 highest-revenue customers
--                 ↓
-- Add their revenue together
--                 ↓
-- Calculate total company revenue using the subquery
--                 ↓
-- Top Customer Revenue ÷ Total Revenue × 100
--                 ↓
--              26.45%
-- =================================================================================================
